Repository Kwonminwoo/KDT_Y_BE_Toy_Project2_work, pull requests merged in 2023-10, with the labels that each got.

#3 Feat: Issue 템플릿 설정
  .github/ISSUE_TEMPLATE/default-issue.md
Labels: documentation

#4 Feat: Pull Request 템플릿을 설정했다
  .github/pull_request_template.md
Labels: documentation

#6 Feat: CI 파일 작성
  .github/workflows/CI.yml
Labels: documentation

#9 main -> develop pull
  .github/workflows/CI.yml
Labels: bug

#8 Feature/#7 spring boot init
  trip_itinerary/.gitignore
  trip_itinerary/build.gradle
  trip_itinerary/gradle/wrapper/gradle-wrapper.jar
  trip_itinerary/gradle/wrapper/gradle-wrapper.properties
  trip_itinerary/gradlew
  trip_itinerary/gradlew.bat
  trip_itinerary/settings.gradle
  trip_itinerary/src/main/java/com/example/trip_itinerary/TripItineraryApplication.java
  trip_itinerary/src/main/resources/application.properties
  trip_itinerary/src/test/java/com/example/trip_itinerary/TripItineraryApplicationTests.java
Labels: enhancement

#12 Feature/#10 set frame
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Accommodation.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Itinerary.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Stay.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Transport.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/repository/ItineraryRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/repository/TripRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
Labels: enhancement

#14 Feat: jpa 의존성 추가 및 설정
  trip_itinerary/build.gradle
  trip_itinerary/src/main/resources/application.properties
  trip_itinerary/src/main/resources/application.yml
Labels: enhancement

#16 Fix: Trip Service 수정
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
Labels: enhancement

#18 Feat: .idea gitignore에 추가
  .gitignore
Labels: enhancement

#20 Feature/#19 get all trips 기능 추가
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
Labels: enhancement

#25 Feature/#23 save trip fix
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Itinerary.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
Labels: enhancement

#26 Feature/search itinerary
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/ItinerarySearchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/repository/ItineraryRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
Labels: enhancement

#34 Feature/#33 add validation exception
  trip_itinerary/build.gradle
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Accommodation.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/AccommodationSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/ItinerarySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/StaySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/TransportSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripListFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripExceptionHandler.java
Labels: enhancement

#40 Feature/#37 all refactoring
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Accommodation.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Itinerary.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Stay.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Transport.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/AccommodationSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/ItinerarySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/StaySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/TransportSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/AccommodationPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/ItineraryPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/StayPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/TransportPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/response/ItineraryErrorResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/response/ItineraryFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/InvalidDateTimeFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/InvalidDateTimeRangeException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryErrorCode.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/repository/ItineraryRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripErrorResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripListFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateRangeException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripErrorCode.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/repository/TripRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/util/DateUtil.java
  trip_itinerary/src/main/resources/application.yml
  trip_itinerary/src/test/java/com/example/trip_itinerary/trip/controller/TripControllerTest.java
  trip_itinerary/src/test/java/com/example/trip_itinerary/trip/service/TripServiceImplTest.java
  trip_itinerary/src/test/resources/application-test.properties
Labels: enhancement

#44 Feature/#43 refactor
  trip_itinerary/src/main/java/com/example/trip_itinerary/TripItineraryApplication.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Accommodation.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Itinerary.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Stay.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Transport.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/AccommodationSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/ItinerarySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/StaySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/TransportSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/response/ItineraryFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/InvalidDateTimeFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/repository/ItineraryRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripListFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateRangeException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/repository/TripRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/util/DateUtil.java
  trip_itinerary/src/main/resources/application.yml
Labels: enhancement

#46 Feat: Trip 오류 수정 및 validation 추가
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/StayPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/TransportPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
Labels: enhancement

#47 Develop
  .gitignore
  README.md
  trip_itinerary/.gitignore
  trip_itinerary/build.gradle
  trip_itinerary/gradle/wrapper/gradle-wrapper.jar
  trip_itinerary/gradle/wrapper/gradle-wrapper.properties
  trip_itinerary/gradlew
  trip_itinerary/gradlew.bat
  trip_itinerary/http/find_all_trip.http
  trip_itinerary/http/find_one_trip.http
  trip_itinerary/http/patch_itinerary.http
  trip_itinerary/http/patch_trip.http
  trip_itinerary/http/save_itinerary.http
  trip_itinerary/http/save_trip.http
  trip_itinerary/settings.gradle
  trip_itinerary/src/main/java/com/example/trip_itinerary/TripItineraryApplication.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/controller/ItineraryController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Accommodation.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Itinerary.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Stay.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/domain/Transport.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/AccommodationSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/ItinerarySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/StaySaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/save/TransportSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/AccommodationPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/ItineraryPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/StayPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/request/update/TransportPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/response/ItineraryErrorResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/dto/response/ItineraryFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/InvalidDateTimeFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/InvalidDateTimeRangeException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryErrorCode.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/exception/ItineraryNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/repository/ItineraryRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/itinerary/service/ItineraryServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/controller/TripController.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/domain/Trip.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripPatchRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/request/TripSaveRequest.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripErrorResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/dto/response/TripListFindResponse.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateFormatException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/InvalidDateRangeException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripErrorCode.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripExceptionHandler.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/exception/TripNotFoundException.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/repository/TripRepository.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripService.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/trip/service/TripServiceImpl.java
  trip_itinerary/src/main/java/com/example/trip_itinerary/util/DateUtil.java
  trip_itinerary/src/main/resources/application.yml
  trip_itinerary/src/test/java/com/example/trip_itinerary/TripItineraryApplicationTests.java
  trip_itinerary/src/test/java/com/example/trip_itinerary/trip/controller/TripControllerTest.java
  trip_itinerary/src/test/java/com/example/trip_itinerary/trip/service/TripServiceImplTest.java
  trip_itinerary/src/test/resources/application-test.properties
Labels: documentation

#49 Feat: Update save_itinerary.http
  trip_itinerary/http/save_itinerary.http
Labels: enhancement
